### ISSUE TITLE
这个情况，有无解决方案

### ISSUE THREAD

**Issue by clzczhc** [AimTao/leancloud-self-wake#1]
云引擎体验实例已达到最大启动时长限制
![image](https://user-images.githubusercontent.com/71619858/146625366-6f003923-1cbc-4998-8781-e0b34327a8d3.png)

**Comment by AimTao** [comment]
云引擎最多运行 18 小时，可以选择 1:00 - 7:00 休眠，7:01 补发休眠期间的邮件。

**Comment by clzczhc** [comment]
> 云引擎最多运行 18 小时，可以选择 1:00 - 7:00 休眠，7:01 补发休眠期间的邮件。

ok，感谢(好像是之前加提醒时，Cronjobs那部分没有停止)
